### ISSUE TITLE
Error when running 'yarn' command

### ISSUE THREAD

**Issue by nickvanderwildt** [niekert/soundify#1]
Hey!

I'm getting an error when trying to run Soundify locally. It says:
`Error: Generated checksum for "electron-v1.6.10-darwin-x64.zip" did not match expected checksum.`

Any ideas on how to fix this? I've tried reinstalling yarn and node, but it doesn't seem to be helping.

**Comment by niekert** [comment]
What version of node / npm are you using? 

There seem to be some issues with npm v5, so could you try running it with another version of npm?

**Comment by nickvanderwildt** [comment]
Late to the reply-party, but that fixed the issue. Thanks 👍
